version:
  server: "1.0.0"

base_url: "http://127.0.0.1:8080"
host: "127.0.0.1"
port: 8080

resource:
  # 상대 경로 사용 (프로젝트 루트 기준)
  # Windows/Mac/Linux 모든 환경에서 작동합니다
  data: "./storage"
  mcp: "./mcp_agent/servers"

path:
  chat: "./chat-data"
  file: "./data-store"
  chroma: "./chroma-db"

log:
  path: "./vibecraft-app-python-log"
